name: delivery

networks:
    dev:
        driver: bridge

services:
    postgres_db:
        image: postgres:latest
        container_name: postgres-delivery
        environment:
            POSTGRES_NAME: 'postgres'
            POSTGRES_PASSWORD: '123'
        ports:
            - "5433:5432"
        networks:
            - dev
        volumes:
            - postgres-data:/var/lib/postgresql/data

    delivery_api:
        image: ${DOCKER_REGISTRY-}delivery-api
        container_name: delivery-api
        build:
            context: .
            dockerfile: ./Systems/Delivery.Systems.DeliveryApi/Dockerfile
        networks:
            - dev
        ports:
           - "8040:8080"
        depends_on:
           - postgres_db

volumes:
  postgres-data: